name = "htmx-design-system-poc"
main = "src/index.tsx"
compatibility_date = "2024-11-14"

# Development settings
[env.development]
workers_dev = true

# Production settings
[env.production]
workers_dev = false
